version: '3'

networks:
  backend:
    external: true

services:

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./DB:/var/lib/mysql
    networks:
      - backend

  express:
    build: ./BackEnd
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - backend

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - ACCESS_KEY_ID=key_aws1
      - AWS_SECRET_ACCESS_KEY=key_aws1
      - DEFAULT_REGION=eu-central-1
      - S3_BUCKET=mes-fichiers
      - TMPDIR=/s3Data/data
      - PLUGIN_BASE_DIR=/plugins
    ports:
      - "4566:4566"
    volumes:
      - ./ServeurFichier/uploads:/s3Data/data
      - ./plugins:/plugins
    #command: /bin/sh -c "chmod +x /plugins/init-localstack.sh && /plugins/init-localstack.sh"
    #command: ["/bin/bash", "/docker-entrypoint-initaws.d/init-localstack.sh"]
    networks:
      - backend

volumes:
  mysql_data:
