version: '3'

networks:
  backend:

services:

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=key_aws1
      - AWS_SECRET_ACCESS_KEY=key_aws1
      - AWS_DEFAULT_REGION=eu-central-1
      - S3_BUCKET=mes-fichiers
      - TMP_DIR=/s3Data/data
    ports:
      - "4566:4566"
    volumes:
      - ./ServeurFichier/uploads:/s3Data/data
      - ./plugins:/plugins
    #command: /bin/sh -c "chmod +x /plugins/init-localstack.sh && /plugins/init-localstack.sh"
    #command: ["/bin/bash", "/docker-entrypoint-initaws.d/init-localstack.sh"]
    networks:
      - backend

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      DATABASE : tpvirtualisation
    volumes:
      - ./DB/Data:/var/lib/mysql
      - ./DB/Init_DB/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - backend

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - backend

  express:
    build: ./BackEnd
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - backend
      
volumes:
  mysql_data:
